pipeline{
 agent any
  stages{
   stage('Checkout Repo') {
    steps{
     script{
      cleanWs()
      checkout([$class: CheckOutClass, branches: [[name: BranchName]], browser: [$class: BrowserClass], userRemoteConfigs: [[credentialsId: PrivateKeyID, url: SourceURL]]])
     }
    }
   }
   stage('clean'){
    steps{
     script{
      sh 'cd ${ApplicationPath}'
      sh 'mvn clean'
     }
    }
   }
   stage('build'){
    steps{
     script{
      sh 'mvn package'
     }
    }
   }
  }
 }