pipeline{
 agent any
  stages{
   stage('Checkout Repo') {
    steps{
     script{
      cleanWs()
      checkout([$class: CheckOutClass, branches: [[name: BranchName]], browser: [$class: BrowserClass], userRemoteConfigs: [[credentialsId: PrivateKeyID, url: SourceURL]]])
     }
    }
   }
   stage('Clean'){
    steps{
     script{
      dir(ApplicationPath) {
       sh 'mvn clean'
      }
     }
    }
   }
   stage('build'){
    steps{
     script{
      dir(ApplicationPath) {
       sh 'mvn package -Dcustom.output.directory=${ArtifactsPath}'
      }
     }
    }
   }
  }
 }
