pipeline{
 agent any
  stages{
   stage('Checkout Repo') {
    steps{
     checkout([$class: CheckOutClass, branches: [[name: BranchName]], browser: [$class: BrowserClass], userRemoteConfigs: [[credentialsId: PrivateKeyID, url: SourceURL]]])
    }
   }
   stage('Clean'){
    steps{
     dir(ApplicationPath) {
      sh '''
       dotnet clean
       if [ -d ${ArtifactsPath} ]
       then
        rm -rf ${ArtifactsPath}/*
       fi
       '''
     }
    }
   }
   stage('Testing'){
    steps{
     dir(ApplicationPath) {
      sh 'dotnet test'
     }
    }
   }
   stage('Build'){
    steps{
     dir(ApplicationPath) {
      sh 'dotnet publish --output ${ArtifactsPath}'
     }
    }
   }
  }
 }
