pipeline{
 agent any
  stages{
   stage('Checkout Repo') {
    steps{
     checkout([$class: CheckOutClass, branches: [[name: BranchName]], browser: [$class: BrowserClass], userRemoteConfigs: [[credentialsId: PrivateKeyID, url: SourceURL]]])
    }
   }
   stage('Clean'){
    steps{
     sh 'rm -rf $ArtifactsPath'
    }
   }
   stage('Install Dependencies')
   {
    steps{
     dir(ApplicationPath) {
      sh 'npm install'
     }
    }
   }
   stage('Generate Executables'){
    steps{
     dir(ApplicationPath) {
      sh 'pkg --out-path $ArtifactsPath app.js'
     }
    }
   }
  }
 }
