pipeline{
 agent any
  stages{
   stage('Checkout Repo') {
    steps{
     checkout([$class: CheckOutClass, branches: [[name: BranchName]], browser: [$class: BrowserClass], userRemoteConfigs: [[credentialsId: PrivateKeyID, url: SourceURL]]])
    }
   }
   stage('Clean'){
    steps{
     dir(ApplicationPath) {
      sh 'docker rmi node:latest 2> temp'
     }
    }
   }
   stage('build'){
    steps{
     dir(ApplicationPath) {
      sh 'docker build -t node:latest .'
     }
    }
   }
  }
 }
