pipeline{
 agent any
  stages{
   stage('Checkout Repo') {
    steps{
     checkout([$class: CheckOutClass, branches: [[name: BranchName]], browser: [$class: BrowserClass], userRemoteConfigs: [[credentialsId: PrivateKeyID, url: SourceURL]]])
    }
   }
   stage('Clean'){
    steps{
     dir(ApplicationPath) {
      sh 'docker rmi -f $(docker images -q node:*) 2> temp || true'
     }
    }
   }
   stage('build'){
    steps{
     dir(ApplicationPath) {
      sh 'docker build -t $ImageName:$BUILD_NUMBER .'
     }
    }
   }
  }
 }
