pipeline{
 agent any
  stages{
   stage('Checkout Repo') {
    steps{
     checkout([$class: CheckOutClass, branches: [[name: BranchName]], browser: [$class: BrowserClass], userRemoteConfigs: [[credentialsId: PrivateKeyID, url: SourceURL]]])
     sh 'ls'
    }
   }
   stage('Clean'){
    steps{
     dir(ApplicationPath) {
      sh '''
       pwd
       ls
       if [ -f $ZipFile ]
       then
        rm $ZipFile
       fi
       if [ -d $DependenciesPath ]
       then
        rm -rf $DependenciesPath
       fi
      '''
     }
    }
   }
   stage('Install Dependencies')
   {
    steps{
     dir(ApplicationPath) {
      sh 'ls'
      sh 'python3 -m pip install -r requirements.txt --target $DependenciesPath'
     }
    }
   }
   stage('Generate Zipped Artifacts'){
    steps{
     dir(ApplicationPath) {
       sh 'ls'
       sh 'tar -cvf $TarFile $ApplicationPath'
       sh 'gzip -f $TarFile'
     }
    }
   }
  }
 }
