pipeline{
 agent any
  stages{
   stage('Checkout Repo') {
    steps{
     checkout([$class: CheckOutClass, branches: [[name: BranchName]], browser: [$class: BrowserClass], userRemoteConfigs: [[credentialsId: PrivateKeyID, url: SourceURL]]])
    }
   }
   stage('Clean'){
    steps{
     dir(ApplicationPath) {
      sh 'ls'
      sh 'rm $ZippedArtifacts'
      sh 'rm -rf $DependenciesPath'
     }
    }
   }
   stage('Install Dependencies')
   {
    steps{
     dir(ApplicationPath) {
      sh 'python3 -m install -r requirements.txt --target $DependenciesPath'
     }
    }
   }
   stage('Generate Zipped Artifacts'){
    steps{
     dir(ApplicationPath) {
       sh 'tar -cvf $TarFile $ApplicationPath'
       sh 'gzip -f $TarFile'
     }
    }
   }
  }
 }
